[package]
name = "rust-date"
version = "0.1.0"
edition = "2021"

# Indique que le projet inclut une bibliothèque et un binaire.
[[bin]]
name = "rust-date"  # Nom du programme principal.

[lib]
name = "rust_date"  # Nom de la bibliothèque.