name: Deploy RustDoc

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Installer Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Générer la documentation
        run: cargo doc --no-deps

      - name: Déployer sur GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: target/doc
